-- AlterTable
ALTER TABLE `tc_positions` MODIFY `devicetime` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    MODIFY `fixtime` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0);

-- AlterTable
ALTER TABLE `tc_statistics` MODIFY `capturetime` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0);
